
import pygame

BRANCO = (255, 255, 255)
PRETO = (0, 0, 0)
CINZAESCURO = (70, 70, 90)
VERDE = (0, 255, 0) 
VERMELHO = (255, 0, 0) 
AZULCLARO = (135, 206, 250) 
CINZACLARO = (176, 196, 222) 
VERDEVENCEDOR = (0,255,0)
LARANJA = (255,140,0)

# constantes do Jogo
TAMANHO_CELULA = 50
LINHAS_TABULEIRO = 10
COLUNAS_TABULEIRO = 10

MARGEM_ESQ_PX = 40
MARGEM_TOP_PX = 30

ESPACO_ENTRE_TABULEIROS = 90
ALTURA_INTERFACE_JOGO = 140

LARGURA_TABULEIRO_PX = COLUNAS_TABULEIRO * TAMANHO_CELULA
ALTURA_TABULEIRO_PX = LINHAS_TABULEIRO * TAMANHO_CELULA

# tamanho final da tela
LARGURA_TELA_PX = MARGEM_ESQ_PX + LARGURA_TABULEIRO_PX + ESPACO_ENTRE_TABULEIROS + LARGURA_TABULEIRO_PX + MARGEM_ESQ_PX
ALTURA_TELA_PX = MARGEM_TOP_PX + ALTURA_TABULEIRO_PX + ALTURA_INTERFACE_JOGO

# MAX_NAVIOS_JOGADOR e INFO_NAVIOS estao no tipos_de_navio por conta da classe BaseNavio